### ISSUE TITLE
Appdata doesn't contain a release tag

### ISSUE THREAD

**Issue by danrabbit** [brain-child/moobo#4]
While reviewing your app, I noticed that your appdata doesn't contain any release tags. For each release, you should have a release tag in AppData describing your most recent changes and including the release date. For the first tag, this can be as simple as something like "First release!"

See the appstream specification for more info on release tags: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

**Comment by pierrefabarius** [comment]
thank you for the hint. resolved
