### ISSUE TITLE
Remove home folder permission scope?

### ISSUE THREAD

**Issue by danrabbit** [brain-child/moobo#5]
While reviewing your app I noticed that you've set permissions for moobo to all of `home`. Can you explain why your app needs these broad filesystem permissions?

**Comment by pierrefabarius** [comment]
Hey Danielle. The user should be able to load images into the app via a filechooser. To access user data I need the permission.

**Comment by danrabbit** [comment]
Hey @pierrefabarius you don't need filesystem permission when using FileChooserNative since it used a portal to grant access to files

**Comment by pierrefabarius** [comment]
Awesome! I made changes to the code :+1:
